name: chatix
description: ChatiX
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0

flutter:
  uses-material-design: true
